name: EU Referendum
favicon: null
layout_spectrum: 0.18192
typography_spectrum: 0.40816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7286771065555513
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
